#!/usr/bin/env bash
set -euo pipefail

# One-time EAS setup for a fresh app cloned from this boilerplate.
# Requires an Expo account: https://expo.dev

if ! command -v npx >/dev/null; then
  echo "npx not found — install Node first." >&2
  exit 1
fi

echo "==> Linking project to EAS (writes projectId into app.json)"
npx eas-cli@latest init

echo "==> Configuring build credentials (Apple + Android keystore)"
echo "    iOS needs an Apple Developer account; Android keystore can be generated by EAS."
npx eas-cli@latest credentials

cat <<'EOF'

==> Push notifications checklist
  1. iOS:    upload an APNs key:      npx eas-cli credentials  (iOS -> Push Notifications)
  2. Android: add google-services.json + FCM V1 key in the Firebase console,
              then: npx eas-cli credentials  (Android -> FCM)
  3. In-app:  expo-notifications is ready to add:
              npx expo install expo-notifications
  Docs: https://docs.expo.dev/push-notifications/overview/

==> Useful commands (already wired in package.json)
  npm run build:ios / build:android      EAS cloud builds (production profile)
  npm run update:preview / update:prod   OTA updates per channel

Done. Commit the updated app.json.
EOF
